--==============================================================================
-- Funções associadas a IDENTITY
--------------------------------------------
-- Criar banco de dados de teste
CREATE DATABASE TESTE_IDENTITY
GO
USE TESTE_IDENTITY;

-- Criar tabela PROFESSOR com campo identidade iniciando em 1 e ---- incrementando 1
CREATE TABLE PROFESSOR
( COD_PROF		INT IDENTITY,
  NOME			VARCHAR(30),
  CONSTRAINT PK_PROFESSOR PRIMARY KEY (COD_PROF) )
-- Criar tabela ALUNO com campo identidade iniciando em 10 e 
-- incrementando 2
CREATE TABLE ALUNO
( COD_ALUNO		INT IDENTITY(10,2),
  NOME			VARCHAR(30),
  CONSTRAINT PK_ALUNO PRIMARY KEY (COD_ALUNO) );


-- Inserir dados na tabela PROFESSOR
INSERT PROFESSOR VALUES ('MAGNO'),('AGNALDO'),('ROBERTO'),
                        ('RENATA'),('EDUARDO'),('MARCIO');
-- Inserir dados na tabela ALUNO
INSERT ALUNO VALUES ('ZÉ DA SILVA'),('CARLOS P. SILVA'),
                    ('ITAMAR COSTA');

-- Consultar as tabelas
SELECT * FROM PROFESSOR
SELECT * FROM ALUNO


DELETE FROM PROFESSOR WHERE COD_PROF = 2

SELECT * FROM PROFESSOR


SET IDENTITY_INSERT PROFESSOR ON
-- OBS.: Não aceita INSERT posicional
INSERT PROFESSOR (COD_PROF, NOME)
VALUES (2,'GODOFREDO')


SET IDENTITY_INSERT PROFESSOR OFF
SELECT * FROM PROFESSOR

SELECT IDENTITYCOL FROM PROFESSOR

SELECT IDENTITYCOL FROM ALUNO


SELECT IDENT_SEED('PROFESSOR')

SELECT IDENT_SEED('ALUNO')


SELECT IDENT_INCR('PROFESSOR')
SELECT IDENT_INCR('ALUNO')


SELECT SCOPE_IDENTITY()

SELECT @@IDENTITY

DELETE FROM PROFESSOR

INSERT INTO PROFESSOR VALUES ('MAGNO')


SELECT * FROM PROFESSOR

DELETE FROM PROFESSOR

-- "Zerar" o contador do IDENTITY
DBCC CHECKIDENT( 'PROFESSOR', RESEED, 0 )

INSERT PROFESSOR VALUES ('MAGNO'),('AGNALDO'),('ROBERTO'),
                        ('RENATA'),('EDUARDO'),('MARCIO');

SELECT * FROM PROFESSOR
