--CROSS APPLY

--Consulta apresentando o código e nome do cliente, Valor total e data da -- emissão. 
SELECT C.CODCLI, C.NOME,P.NUM_PEDIDO,P.VLR_TOTAL, P.DATA_EMISSAO
FROM TB_CLIENTE AS C
JOIN TB_PEDIDO AS P ON P.CODCLI = C.CODCLI 
ORDER BY C.CODCLI,P.NUM_PEDIDO


--Adicionando as colunas quantidade de pedidos, maior e menor valor de compra e a última data de pedido.

SELECT  C.CODCLI, C.NOME,P.NUM_PEDIDO,P.VLR_TOTAL, P.DATA_EMISSAO,
(SELECT COUNT(*) FROM TB_PEDIDO 
	WHERE CODCLI = C.CODCLI) AS QTD_PED,
(SELECT MAX(VLR_TOTAL) FROM TB_PEDIDO 
	WHERE CODCLI = C.CODCLI) AS MAIOR_VALOR,
(SELECT MIN(VLR_TOTAL) FROM TB_PEDIDO 
	WHERE CODCLI = C.CODCLI) AS MENOR_VALOR,
(SELECT MAX(DATA_EMISSAO) FROM TB_PEDIDO 
	WHERE CODCLI = C.CODCLI) AS ULTIMA_COMPRA
 FROM TB_CLIENTE AS C
JOIN TB_PEDIDO AS P ON P.CODCLI = C.CODCLI 
ORDER BY C.CODCLI,P.NUM_PEDIDO


---Utilizando o CROSS APPLY
SELECT	C.CODCLI,C.NOME,P.NUM_PEDIDO,P.VLR_TOTAL, P.DATA_EMISSAO,
		CR.QTD_PED, CR.MAIOR_VALOR , CR.MENOR_VALOR ,   
           CR.DATAMAXIMA 	
 FROM TB_CLIENTE AS C
 JOIN TB_PEDIDO AS P ON P.CODCLI = C.CODCLI 
 CROSS APPLY
 ( SELECT	COUNT(*) AS QTD_PED, 
			MAX(VLR_TOTAL) AS MAIOR_VALOR,
			MIN(VLR_TOTAL) AS MENOR_VALOR,
			MAX(DATA_EMISSAO) AS DATAMAXIMA 
 FROM TB_PEDIDO  AS P
 WHERE C.CODCLI = P.CODCLI ) AS CR
ORDER BY C.CODCLI,P.NUM_PEDIDO

-- Consulta com filtro dos pedidos de 2014.

SELECT  C.CODCLI, C.NOME,P.NUM_PEDIDO,P.VLR_TOTAL, P.DATA_EMISSAO,
(SELECT COUNT(*) FROM TB_PEDIDO 
	WHERE YEAR(DATA_EMISSAO) = 2014 
	AND CODCLI = C.CODCLI) AS QTD_PED,
(SELECT MAX(VLR_TOTAL) FROM TB_PEDIDO 
	WHERE YEAR(DATA_EMISSAO) = 2014 
	AND CODCLI = C.CODCLI) AS MAIOR_VALOR,
(SELECT MIN(VLR_TOTAL) FROM TB_PEDIDO 
	WHERE YEAR(DATA_EMISSAO) = 2014 
	AND CODCLI = C.CODCLI) AS MENOR_VALOR,
(SELECT MAX(DATA_EMISSAO) FROM TB_PEDIDO 
	WHERE YEAR(DATA_EMISSAO) = 2014 
	AND CODCLI = C.CODCLI) AS ULTIMA_COMPRA
 FROM TB_CLIENTE AS C
JOIN TB_PEDIDO AS P ON P.CODCLI = C.CODCLI 
WHERE  YEAR(DATA_EMISSAO) = 2014


--UTILIZANDO O CROSS APPLY

SELECT	C.CODCLI, C.NOME,P.NUM_PEDIDO,P.VLR_TOTAL, P.DATA_EMISSAO,
		CR.QTD_PED, CR.MAIOR_VALOR , CR.MENOR_VALOR , CR.DATAMAXIMA 
FROM TB_CLIENTE AS C
JOIN TB_PEDIDO AS P ON P.CODCLI = C.CODCLI 
CROSS APPLY
 ( SELECT	COUNT(*) AS QTD_PED, 
			MAX(VLR_TOTAL) AS MAIOR_VALOR,
			MIN(VLR_TOTAL) AS MENOR_VALOR,
			MAX(DATA_EMISSAO) AS DATAMAXIMA 
 FROM TB_PEDIDO  AS PC
 WHERE C.CODCLI = PC.CODCLI AND YEAR(PC.DATA_EMISSAO) = 2014 )AS CR
WHERE  YEAR(P.DATA_EMISSAO) = 2014
ORDER BY C.CODCLI,P.NUM_PEDIDO


SELECT D.DEPTO , E.NOME 
FROM TB_DEPARTAMENTO AS D
LEFT JOIN TB_EMPREGADO AS E ON E.COD_DEPTO = D.COD_DEPTO 
ORDER BY 2

SELECT D.DEPTO , CA.NOME 
FROM TB_DEPARTAMENTO AS D
CROSS APPLY 
(SELECT E.NOME FROM TB_EMPREGADO  AS E WHERE E.COD_DEPTO = D.COD_DEPTO ) AS CA
ORDER BY 2

SELECT D.DEPTO , E.NOME 
FROM TB_DEPARTAMENTO AS D
LEFT JOIN TB_EMPREGADO AS E ON E.COD_DEPTO = D.COD_DEPTO 
ORDER BY 2


SELECT D.DEPTO , CA.NOME 
FROM TB_DEPARTAMENTO AS D
OUTER  APPLY 
(SELECT E.NOME FROM TB_EMPREGADO  AS E WHERE E.COD_DEPTO = D.COD_DEPTO ) AS CA
ORDER BY 2





