SELECT * 
FROM TB_VENDEDOR

CREATE TABLE PESSOA
(COD INT,
NOME VARCHAR(40)
)
INSERT PESSOA
VALUES (3,'PATRICIA'),
		(1,'ANDERSON'),
		(2,'MARIA')
		SELECT * 
		FROM PESSOA
CREATE NONCLUSTERED INDEX NDX_COD ON PESSOA(COD)
INSERT PESSOA
VALUES (5,'VALERIA'),
		(4,'PEDRO')

		DROP TABLE PESSOA
		CREATE TABLE PESSOA
		(COD INT PRIMARY KEY,
		NOME VARCHAR(40)
		)
		INSERT PESSOA
VALUES (3,'PATRICIA'),
		(1,'ANDERSON'),
		(2,'MARIA')


		SELECT CODCLI, NOME, ESTADO FROM TB_CLIENTE WHERE ESTADO='SP'


		CREATE NONCLUSTERED INDEX NDX_ESTADO ON TB_CLIENTE(ESTADO)

CREATE INDEX NDX_CLIENTE_INCLUDE ON TB_CLIENTE (NOME) INCLUDE
(ESTADO)

---APAGAR INDICE
DROP INDEX TB_CLIENTE.NDX_CLIENTE_INCLUDE

