--IDENTITY(AUTONUMERAÇÃO)
CREATE DATABASE TESTE_IDENTITY
--COLOCAR O BANCO DE DADOS EM USO
USE TESTE_IDENTITY
--CRIAR A TABELA PROFESSOR
CREATE TABLE PROFESSOR
( COD_PROF INT IDENTITY(1,1)
,NOME VARCHAR(30)
,CONSTRAINT PK_PROFESSOR PRIMARY KEY (COD_PROF) )

CREATE TABLE ALUNO
( COD_ALUNO INT IDENTITY(10,2)
,NOME VARCHAR(30)
,CONSTRAINT PK_ALUNO PRIMARY KEY (COD_ALUNO) 
SELECT *
FROM PROFESSOR 

INSERT PROFESSOR 
VALUES ('MAGNO')
      ,('AGNALDO')
      ,('ROBERTO')
      ,('RENATA')
      ,('EDUARDO')
      ,('MARCIO')

SELECT *
FROM ALUNO

-- Inserir dados na tabela ALUNO
INSERT ALUNO 
VALUES ('ZÉ DA SILVA'),('CARLOS P. SILVA'),
('ITAMAR COSTA')
--APAGAR O REGISTRO DE CODIGO 2 NA TABELA 
--PROFESSOR
BEGIN TRAN
DELETE
FROM PROFESSOR
WHERE COD_PROF=2

SELECT *
FROM PROFESSOR
--PERMITIR A INSERÇÃO COM O IDENTITY
SET IDENTITY_INSERT PROFESSOR ON 
--INSERT DECLARATIVO
INSERT INTO PROFESSOR(COD_PROF 
                      ,NOME)
VALUES(2,'MARIA ANTONIA')
SET IDENTITY_INSERT PROFESSOR OFF
COMMIT
--APAGAR O REGISTRO QUE TEM O NOME RENATA
DELETE 
FROM PROFESSOR 
WHERE COD_PROF=4
--INSERIR UM REGISTRO QUE TENHA O MESMO CODIGO
--DA PROFESSORA RENATA
SET IDENTITY_INSERT PROFESSOR ON
INSERT INTO PROFESSOR(COD_PROF
                      ,NOME)
VALUES(4,'VAGNER')
SELECT *
FROM PROFESSOR 
SET IDENTITY_INSERT PROFESSOR OFF
--IDENTIFICAR A COLUNA COM AUTONUMERAÇÃO
SELECT IDENTITYCOL FROM PROFESSOR
SELECT IDENTITYCOL FROM ALUNO
------------------------------------------------
--VALOR INICIAL DO IDENTITY
SELECT IDENT_SEED('PROFESSOR')
--INCREMENTO DO IDENTITY
SELECT IDENT_INCR('PROFESSOR')
--APRESENTE O VALOR INICIAL DO IDENTITY PARA
--A TABELA ALUNO
SELECT IDENT_SEED('ALUNO')
--APRESENTE O VALOR INCREMENTO DO IDENTITY PARA
--A TABELA ALUNO
SELECT IDENT_INCR('ALUNO')
-----------------------------------------------
SELECT SCOPE_IDENTITY()
SELECT @@IDENTITY
-----------------------------------------------
--ULTIMO VALOR AUTONUMERAÇÃO DE UMA TABELA
SELECT IDENT_CURRENT ('PROFESSOR')
SELECT IDENT_CURRENT ('ALUNO')
-----------------------------------------------
--APAGAR TODOS OS REGISTROS DA TABELA PROFESSOR
DELETE
FROM PROFESSOR

SELECT *
FROM PROFESSOR 
INSERT INTO PROFESSOR
VALUES('JANAINA')
--REINICIAR O AUTONUMERAÇÃO(IDENTITY)
DELETE
FROM PROFESSOR
DBCC CHECKIDENT('PROFESSOR',RESEED,0)

SELECT *
FROM PROFESSOR
--VISUALIZAR A ESTRUTURA DA TABELA
EXEC SP_HELP PROFESSOR
-------------------------------------------
--COLOCAR EM USO O BANCO DE DADOS PEDIDOS
USE Pedidos
--COPIA DA TABELA EMPREGADO
SELECT * INTO EMP_TEMP
FROM TB_EMPREGADO 

SELECT *
FROM EMP_TEMP
--APAGAR OS REGISTROS COM COD_CARGO=3
DELETE
FROM EMP_TEMP
OUTPUT deleted.*
WHERE COD_CARGO=3
------------------------------------------------
UPDATE EMP_TEMP 
SET SALARIO = SALARIO * 1.0
OUTPUT deleted.*
WHERE COD_DEPTO = 2
SET IDENTITY_INSERT EMP_TEMP ON
SELECT COUNT(*)
FROM EMP_TEMP
SELECT COUNT(*)
FROM TB_EMPREGADO
--AS TABELAS EMP_TEMP E TB_EMPREGADO DEVEM SER
--IGUAIS, OU SEJA, TER A MESMA QUANTIDADE DE 
--REGISTROS E O MESMO CONTEUDO PARA OS CAMPOS
--EMP_TEMP É A TABELA ALVO
--TB_EMPREGADO É A TABELA FONTE
SET IDENTITY_INSERT EMP_TEMP ON
MERGE EMP_TEMP AS EMP
USING TB_EMPREGADO AS TB_EMP
ON EMP.CODFUN=TB_EMP.CODFUN
WHEN MATCHED AND EMP.SALARIO<>TB_EMP.SALARIO THEN
UPDATE
SET EMP.SALARIO=TB_EMP.SALARIO

WHEN NOT MATCHED THEN
INSERT (CODFUN,NOME,COD_DEPTO
       ,COD_CARGO,DATA_ADMISSAO
       ,DATA_NASCIMENTO,SALARIO
       , NUM_DEPEND, SINDICALIZADO
       , OBS, FOTO)
VALUES (CODFUN,NOME,COD_DEPTO
        ,COD_CARGO,DATA_ADMISSAO
        ,DATA_NASCIMENTO,SALARIO
        , NUM_DEPEND, SINDICALIZADO
        , OBS, FOTO);
SET IDENTITY_INSERT EMP_TEMP OFF
--
SELECT *
FROM SYSOBJECTS
WHERE XTYPE='U'
SELECT *
FROM SYS.OBJECTS
WHERE OBJECT_ID=1454628225
--APAGAR A TABELA EMP_TEMP
IF OBJECT_ID('EMP_TEMP','U') IS NOT NULL
DROP TABLE EMP_TEMP
SELECT * INTO EMP_TEMP
FROM TB_EMPREGADO
------------------------------------------------
--MEREGE COM OUTPUT
--PREPARAR A TABELA EMP_TEMP
DELETE 
FROM EMP_TEMP 
WHERE COD_CARGO IN (3,5,7)
-------------------------------------------------
UPDATE EMP_TEMP 
SET SALARIO *= 1.2
WHERE COD_DEPTO = 2
-------------------------------------------------
INSERT INTO EMP_TEMP
(NOME, COD_DEPTO, COD_CARGO
,SALARIO, DATA_ADMISSAO)
VALUES ('MARIA ANTONIA',1,2
        ,2000,GETDATE())
       ,('ANTONIA MARIA',2,1,3000,GETDATE())
SELECT *
FROM EMP_TEMP
ORDER BY CODFUN 
SET IDENTITY_INSERT EMP_TEMP ON
MERGE EMP_TEMP AS EMPT
USING TB_EMPREGADO AS EMP
ON EMPT.CODFUN=EMP.CODFUN

WHEN MATCHED AND EMPT.SALARIO <> EMP.SALARIO THEN
UPDATE 
SET EMPT.SALARIO=EMP.SALARIO

WHEN NOT MATCHED THEN
INSERT (CODFUN,NOME,COD_DEPTO
       ,COD_CARGO,DATA_ADMISSAO
       , DATA_NASCIMENTO
       ,SALARIO, NUM_DEPEND
       , SINDICALIZADO, OBS, FOTO)
VALUES (CODFUN,NOME,COD_DEPTO,COD_CARGO
       ,DATA_ADMISSAO, DATA_NASCIMENTO
       ,SALARIO, NUM_DEPEND, SINDICALIZADO
       , OBS, FOTO)
WHEN NOT MATCHED BY SOURCE THEN
DELETE 
OUTPUT $ACTION AS ACAO
      ,INSERTED.CODFUN AS [Código Após]
      ,DELETED.CODFUN AS [Código Antes]
      ,INSERTED.NOME AS [Nome Após]
      ,DELETED.NOME AS [Nome Antes]
      ,INSERTED.SALARIO AS [Salário Após]
      ,DELETED.SALARIO AS [Salário Antes];
SET IDENTITY_INSERT EMP_TEMP OFF
-----------------------------------------------
--PIVOT
SELECT CODVEN
     , MONTH(DATA_EMISSAO) AS MES
     , YEAR(DATA_EMISSAO) AS ANO
     , SUM(VLR_TOTAL) AS TOT_VENDIDO
FROM TB_PEDIDO
WHERE YEAR(DATA_EMISSAO) = 2014
GROUP BY CODVEN , MONTH(DATA_EMISSAO)
       , YEAR(DATA_EMISSAO)
ORDER BY 1,2,3
---------------------------------------------
SELECT CODVEN,[1] AS JAN, [2] AS FEV
             ,[3] AS MAR, [4] AS ABR
             ,[5] AS MAI, [6] AS JUN
             ,[7] AS JUL, [8] AS AGO
             ,[9] AS [SET], [10] AS [OUT]
             ,[11] AS NOV, [12] AS DEZ
FROM(SELECT CODVEN,VLR_TOTAL,MONTH(DATA_EMISSAO) AS MES
     FROM TB_PEDIDO AS PED
     WHERE YEAR(DATA_EMISSAO)=2014) AS DADOS
PIVOT(SUM(VLR_TOTAL) FOR MES IN ([1],[2],[3]
															,[4],[5],[6]
															,[7],[8],[9]
												,[10],[11],[12])) AS GIRO
----------------------------------------------------------------------
--EXERCICIO
--ACRESCENTAR O CAMPO NOME DO VENDEDOR
SELECT CODVEN, NOME, [1] AS JAN, [2] AS FEV
             ,[3] AS MAR, [4] AS ABR
             ,[5] AS MAI, [6] AS JUN
             ,[7] AS JUL, [8] AS AGO
             ,[9] AS [SET], [10] AS [OUT]
             ,[11] AS NOV, [12] AS DEZ
FROM(SELECT PED.CODVEN, VEND.NOME,PED.VLR_TOTAL
           ,MONTH(PED.DATA_EMISSAO) AS MES
     FROM TB_PEDIDO AS PED
     INNER JOIN TB_VENDEDOR AS VEND
     ON VEND.CODVEN=PED.CODVEN
     WHERE YEAR(DATA_EMISSAO)=2014) AS DADOS
PIVOT(SUM(VLR_TOTAL) FOR MES IN ([1],[2],[3]
															,[4],[5],[6]
															,[7],[8],[9]
												,[10],[11],[12])) AS GIRO

--CRIAR UMA CONSULTA PARA RETORNAR O TOTAL PEDIDO(VLR_TOTAL) POR CLIENTE
--NO ANO DE 2014 NOS MESES DE JAN A DEZ

SELECT CODCLI, NOME, [1] AS JAN, [2] AS FEV
             ,[3] AS MAR, [4] AS ABR
             ,[5] AS MAI, [6] AS JUN
             ,[7] AS JUL, [8] AS AGO
             ,[9] AS [SET], [10] AS [OUT]
             ,[11] AS NOV, [12] AS DEZ
FROM(SELECT CLI.CODCLI, CLI.NOME,PED.VLR_TOTAL
           ,MONTH(PED.DATA_EMISSAO) AS MES
     FROM TB_PEDIDO AS PED
     INNER JOIN TB_CLIENTE AS CLI
     ON CLI.CODCLI=PED.CODCLI
     WHERE YEAR(DATA_EMISSAO)=2014) AS DADOS
PIVOT(SUM(VLR_TOTAL) FOR MES IN ([1],[2],[3]
															,[4],[5],[6]
															,[7],[8],[9]
												,[10],[11],[12])) AS GIRO

--UNPIVOT
CREATE TABLE FREQ_CINEMA
( DIA_SEMANA TINYINT,
SEC_14HS INT,
SEC_16HS INT,
SEC_18HS INT,
SEC_20HS INT,
SEC_22HS INT )

INSERT FREQ_CINEMA VALUES ( 1, 80, 100, 130, 90, 70 )
INSERT FREQ_CINEMA VALUES ( 2, 20, 34, 75, 50, 30 )
INSERT FREQ_CINEMA VALUES ( 3, 25, 40, 80, 70, 25 )
INSERT FREQ_CINEMA VALUES ( 4, 30, 45, 70, 50, 30 )
INSERT FREQ_CINEMA VALUES ( 5, 35, 40, 60, 60, 40 )
INSERT FREQ_CINEMA VALUES ( 6, 25, 34, 70, 90, 110 )
INSERT FREQ_CINEMA VALUES ( 7, 30, 80, 130, 150, 180 )

SELECT *
FROM FREQ_CINEMA
----------------------------------------------------------

SELECT DIA_SEMANA, HORARIO, QTD_PESSOAS
FROM (SELECT DIA_SEMANA
           , SEC_14HS
           , SEC_16HS
           , SEC_18HS
           , SEC_20HS
           , SEC_22HS
FROM FREQ_CINEMA) AS DADOS_CINE
UNPIVOT ( QTD_PESSOAS FOR HORARIO IN (SEC_14HS, SEC_16HS, SEC_18HS,
                                      SEC_20HS, SEC_22HS)) AS GIRO
-------------------------------------------------------------------------
SELECT MONTH( DATA_EMISSAO ) AS MES
      ,YEAR( DATA_EMISSAO ) AS ANO
      ,MAX( VLR_TOTAL ) AS MAIOR_PEDIDO
FROM TB_PEDIDO
WHERE YEAR(DATA_EMISSAO) = 2014
GROUP BY MONTH(DATA_EMISSAO), YEAR(DATA_EMISSAO)
ORDER BY 1
---CTE
WITH BUSCAPED (MES, ANO,MAIOR_PEDIDO)
AS
(
SELECT MONTH( DATA_EMISSAO ) AS MES
      ,YEAR( DATA_EMISSAO ) AS ANO
      ,MAX( VLR_TOTAL ) AS MAIOR_PEDIDO
FROM TB_PEDIDO
WHERE YEAR(DATA_EMISSAO) = 2014
GROUP BY MONTH(DATA_EMISSAO), YEAR(DATA_EMISSAO)
)

SELECT BUSCAPED.MES
      ,BUSCAPED.ANO
      ,BUSCAPED.MAIOR_PEDIDO
      ,TB_PEDIDO.NUM_PEDIDO
FROM BUSCAPED
INNER JOIN TB_PEDIDO
ON BUSCAPED.MES=MONTH(TB_PEDIDO.DATA_EMISSAO )
AND BUSCAPED.ANO=YEAR(TB_PEDIDO.DATA_EMISSAO )
AND BUSCAPED.MAIOR_PEDIDO=TB_PEDIDO.VLR_TOTAL

--CTE RECURSIVA
WITH CONTADOR(N)
AS
(
SELECT 1
UNION ALL
SELECT N+1 FROM CONTADOR
WHERE N<10
)
SELECT *
FROM CONTADOR
--CROSS APPLY
SELECT C.CODCLI, C.NOME,P.NUM_PEDIDO
      ,P.VLR_TOTAL, P.DATA_EMISSAO
      , (SELECT COUNT(*) 
         FROM TB_PEDIDO
         WHERE CODCLI = C.CODCLI) AS QTD_PED
       ,(SELECT MAX(VLR_TOTAL) FROM TB_PEDIDO
         WHERE CODCLI = C.CODCLI) AS MAIOR_VALOR
FROM TB_CLIENTE AS C
JOIN TB_PEDIDO AS P ON P.CODCLI = C.CODCLI
ORDER BY C.CODCLI,P.NUM_PEDIDO
--CROSS APPLY
SELECT C.CODCLI,C.NOME,P.NUM_PEDIDO
      ,P.VLR_TOTAL, P.DATA_EMISSAO
      ,CR.QTD_PED, CR.MAIOR_VALOR
FROM TB_CLIENTE AS C
JOIN TB_PEDIDO AS P 
ON P.CODCLI = C.CODCLI

CROSS APPLY
( SELECT COUNT(*) AS QTD_PED
         ,MAX(VLR_TOTAL) AS MAIOR_VALOR
  FROM TB_PEDIDO AS P
  WHERE C.CODCLI=P.CODCLI ) AS CR
ORDER BY CR.QTD_PED

SELECT D.DEPTO , E.NOME
FROM TB_DEPARTAMENTO AS D
JOIN TB_EMPREGADO AS E 
ON E.COD_DEPTO = D.COD_DEPTO
ORDER BY E.NOME


SELECT D.DEPTO , CA.NOME
FROM TB_DEPARTAMENTO AS D
CROSS APPLY
(SELECT E.NOME 
FROM TB_EMPREGADO AS E 
WHERE E.COD_DEPTO = D.COD_DEPTO ) AS CA
ORDER BY CA.NOME
-----------------------------------------------------------------------

SELECT D.DEPTO , E.NOME
FROM TB_DEPARTAMENTO AS D LEFT JOIN TB_EMPREGADO AS E 
ON E.COD_DEPTO = D.COD_DEPTO
ORDER BY 2

--OUTER APPLY

SELECT D.DEPTO , CA.NOME
FROM TB_DEPARTAMENTO AS D
OUTER APPLY
(SELECT E.NOME 
FROM TB_EMPREGADO AS E 
WHERE E.COD_DEPTO = D.COD_DEPTO ) AS CA
ORDER BY 2
-------------------------------------------------------------------------
--EXERCICIO LAB2 A, B,C
-------------------------------------------------------------------------
--CAPITULO 3 - TIPOS DE DADOS
--CRIAR OS TIPOS DE DADOS:
--TIPO_NOME --> VARCHAR(60)
--TIPO_ENDERECO --> VARCHAR(60)

CREATE TYPE TIPO_NOME
FROM VARCHAR(60) NOT NULL
--VISUALIZAR O TIPO DE DADOS CRIADO PELO USUARIO
SELECT *
FROM SYSTYPES
CREATE TYPE TIPO_ENDERECO
FROM VARCHAR(60) NOT NULL
--ASSOCIAR O TIPO DE DADOS AO CAMPO DA TABELA
CREATE TABLE PESSOA
(COD INT PRIMARY KEY
,NOME TIPO_NOME
,ENDERECO TIPO_ENDERECO
,CNPJ BIGINT
)
--VISUALIZAR A ESTRUTURA DA TABELA
EXEC SP_HELP PESSOA
--EXERCICIO
--CRIAR UM BANCO DE DADOS COM O NOME TESTE_UDDT
CREATE DATABASE TESTE_UDDT
USE TESTE_UDDT
--CRIAR OS TIPOS DE DADOS: TYPE_NOME_PESSOA, TYPE_NOME_EMPRESA
--TYPE_PRECO, TYPE_SN, TYPE_DATA_MOVTO
CREATE TYPE TYPE_NOME_PESSOA
FROM VARCHAR(60) NOT NULL

CREATE TYPE TYPE_NOME_EMPRESA
FROM VARCHAR(60) NOT NULL

CREATE TYPE TYPE_PRECO
FROM NUMERIC(12,2)

CREATE TYPE TYPE_SN
FROM CHAR(1) NOT NULL

CREATE TYPE TYPE_DATA_MOVTO
FROM DATETIME NOT NULL

SELECT *
FROM SYSTYPES
WHERE UID=1
--REGRAS DE VALIDAÇÃO
--O PRECO NÃO PODE SER NEGATIVO
CREATE RULE R_PRECO AS @PRECO>=0
GO
CREATE RULE R_SN AS @SN IN('S','N')
GO
CREATE RULE R_DATA_MOVTO AS @DT <= GETDATE()

SELECT *
FROM SYSOBJECTS
WHERE XTYPE='R'


SELECT *
FROM SYSCOMMENTS

SELECT NAME
      ,TEXT
FROM SYSOBJECTS AS OBJ
INNER JOIN SYSCOMMENTS AS S
ON OBJ.ID=S.ID
WHERE OBJ.XTYPE='R'
-----------------------------------------------------------
--ASSOCIAR A REGRA AO TIPO DE DADOS
EXEC SP_BINDRULE 'R_PRECO','TYPE_PRECO'
EXEC SP_BINDRULE 'R_SN','TYPE_SN'
EXEC SP_BINDRULE 'R_DATA_MOVTO','TYPE_DATA_MOVTO'
------------------------------------------------------------
--O TIPO DE DADOS SN DEVE RECEBER POR DEFAULT A LETRA 'S'
CREATE DEFAULT DEF_SN AS 'S'
GO
--DATA_MOVTO POR DEFAULT RECEBE GETDATE()
CREATE DEFAULT DEF_DATA_MOVTO AS GETDATE()
-------------------------------------------------------------
--ASSOCIAR O DEFAULT AO TIPO DE DADOS
EXEC SP_BINDEFAULT 'DEF_SN', 'TYPE_SN'
EXEC SP_BINDEFAULT 'DEF_DATA_MOVTO', 'TYPE_DATA_MOVTO'
--------------------------------------------------------------
CREATE TABLE PRODUTOS
( COD_PROD INT IDENTITY(1,1),
DESCRICAO VARCHAR(80),
PRECO_CUSTO TYPE_PRECO,
PRECO_VENDA TYPE_PRECO,
DATA_CADASTRO TYPE_DATA_MOVTO,
SN_ATIVO TYPE_SN,
CONSTRAINT PK_PRODUTOS PRIMARY KEY (COD_PROD) )
--TESTAR OS TIPOS DE DADOS
INSERT INTO PRODUTOS( DESCRICAO, PRECO_CUSTO, PRECO_VENDA )
VALUES( 'TESTE 1', 10.50, 2.58 )

INSERT INTO PRODUTOS( DESCRICAO, PRECO_CUSTO, PRECO_VENDA
                      ,DATA_CADASTRO )
VALUES( 'TESTE 2', 10.50, 2.58,'2019/05/17' )

INSERT INTO PRODUTOS( DESCRICAO, PRECO_CUSTO, PRECO_VENDA
                      ,DATA_CADASTRO,SN_ATIVO  )
VALUES( 'TESTE 3', 0.50,1.5,GETDATE(),'N' )
SELECT *
FROM PRODUTOS
-----------------------------------------------------------------
CREATE SEQUENCE SEQ_ALUNO
START WITH 1000
INCREMENT BY 10
MINVALUE 10
MAXVALUE 10000
CYCLE CACHE 10

CREATE TABLE T_ALUNO
(COD_ALUNO INT,
NOM_ALUNO VARCHAR(50) )
SELECT *
FROM T_ALUNO

INSERT INTO T_ALUNO (COD_ALUNO, NOM_ALUNO)
VALUES (NEXT VALUE FOR DBO.SEQ_ALUNO, 'TESTE2')

CREATE SYNONYM TESTE_AL FOR DBO.T_ALUNO
SELECT *
FROM TESTE_AL
-----------------------------------------------------------------
--CAPITULO 4
--PLANO DE EXECUÇÃO
USE PEDIDOS
SELECT *
FROM TB_PRODUTO

SELECT D.DEPTO , E.NOME
FROM TB_DEPARTAMENTO AS D
JOIN TB_EMPREGADO AS E 
ON E.COD_DEPTO = D.COD_DEPTO
ORDER BY E.NOME


MERGE EMP_TEMP AS EMP
USING TB_EMPREGADO AS TB_EMP
ON EMP.CODFUN=TB_EMP.CODFUN
WHEN MATCHED AND EMP.SALARIO<>TB_EMP.SALARIO THEN
UPDATE
SET EMP.SALARIO=TB_EMP.SALARIO

WHEN NOT MATCHED THEN
INSERT (CODFUN,NOME,COD_DEPTO
       ,COD_CARGO,DATA_ADMISSAO
       ,DATA_NASCIMENTO,SALARIO
       , NUM_DEPEND, SINDICALIZADO
       , OBS, FOTO)
VALUES (CODFUN,NOME,COD_DEPTO
        ,COD_CARGO,DATA_ADMISSAO
        ,DATA_NASCIMENTO,SALARIO
        , NUM_DEPEND, SINDICALIZADO
        , OBS, FOTO);








































