--identity (autonumeração

CREATE DATABASE TESTE_IDENTITY
GO
USE TESTE_IDENTITY;
-- Criar tabela PROFESSOR com campo identidade iniciando em 1 e ----
incrementando 1
CREATE TABLE PROFESSOR
( COD_PROF INT IDENTITY,
 NOME VARCHAR(30),
 CONSTRAINT PK_PROFESSOR PRIMARY KEY (COD_PROF) )
-- Criar tabela ALUNO com campo identidade iniciando em 10 e
-- incrementando 2
CREATE TABLE ALUNO
( COD_ALUNO INT IDENTITY(10,2),
 NOME VARCHAR(30),
 CONSTRAINT PK_ALUNO PRIMARY KEY (COD_ALUNO) );

 SELECT * FROM ALUNO

 -- Inserir dados na tabela PROFESSOR
INSERT PROFESSOR VALUES ('MAGNO'),('AGNALDO'),('ROBERTO'),
 ('RENATA'),('EDUARDO'),('MARCIO');
-- Inserir dados na tabela ALUNO
INSERT ALUNO VALUES ('ZÉ DA SILVA'),('CARLOS P. SILVA'),
 ('ITAMAR COSTA');
-- Consultar as tabelas
SELECT * FROM PROFESSOR
SELECT * FROM ALUNO


DELETE FROM PROFESSOR WHERE COD_PROF = 2
SELECT * FROM PROFESSOR

--PERMITIR A INSERÇÃO COM IDENTITY

SET IDENTITY_INSERT PROFESSOR ON
INSERT PROFESSOR (COD_PROF, NOME)
VALUES (2,'MARIA ANTONIA')SELECT * FROM PROFESSORSET IDENTITY_INSERT PROFESSOR OFF--APAGAR O REGISTRO QUE TEM O NOME RENATA--INSERIR UM REGISTRO QUE TENHA O MESMO CODIGO--DA PROFESSORA RENATADELETE FROM PROFESSOR WHERE COD_PROF = 4SET IDENTITY_INSERT PROFESSOR ON
INSERT PROFESSOR (COD_PROF, NOME)
VALUES (4,'VAGNER')SELECT * FROM PROFESSORSET IDENTITY_INSERT PROFESSOR OFF--IDENTIFICAR A COLUNA COM AUTONUMERAÇÃOSELECT IDENTITYCOL FROM PROFESSORSELECT IDENTITYCOL FROM ALUNO--VALOR INICIAL DO IDENTITYSELECT IDENT_SEED('PROFESSOR')--INCREMENTO DO IDENTITYSELECT IDENT_INCR('PROFESSOR')--APRESENTE O VALOR INCREMENTO DO IDENTITY PARA--A TABELA ALUNOSELECT IDENT_SEED('ALUNO')
SELECT IDENT_INCR('ALUNO')--ULTIMO VALOR DE AUTONUMERAÇÃOSELECT SCOPE_IDENTITY()SELECT IDENT_CURRENT ('PROFESSOR')--APAGAR TODOS OS REGISTROS TA TABELA PROFESSORDELETEFROM PROFESSORINSERT INTO PROFESSORVALUES ('JANAINA')SELECT * FROM PROFESSOR--REINICIAR A AUTONUMERAÇÃO ( IDENTITY)DBCC CHECKIDENT('PROFESSOR',RESEED, 0)SELECT * FROM PROFESSORSELECT IDENT_CURRENT ('ALUNO')INSERT INTO PROFESSORVALUES ('THIAGO')--VISUALIZAR A ESTRUTURA DA TABELAEXEC sp_help PROFESSOR
